### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'lin_node_3'

### ISSUE THREAD

**Issue by AbbasRahimi** [lingchen0331/HGEN#2]
Hello, 
The code works well on the "IMDB_movie" dataset, but when I'm trying to run the code on one of ["syn_100", "syn_200", "syn_500"] datasets, it ran into Attribute Error: 'Generator' object has no attribute 'lin_node_3'.

**Comment by lingchen0331** [comment]
Hi, perhaps you should try [hgen_syn.py](https://github.com/lingchen0331/HGEN/blob/main/hgen_syn.py)?

**Comment by AbbasRahimi** [comment]
Yes, it works well with [hgen_syn.py](https://github.com/lingchen0331/HGEN/blob/main/hgen_syn.py). Thanks a lot!
